version: '2'
services:
  database:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: csa
      MYSQL_USER: csa
      MYSQL_PASSWORD: csa
    ports:
      - 3306:3306
