drop table if exists ss_actions;
create table ss_actions (
  id bigint generated by default as identity (start with 1),
  jiraKey varchar(255),
  userId varchar(1024),
  userName varchar(1024),
  actionType varchar(255),
  actionStatus varchar(255),
  body varchar(4096),
  idp varchar(255),
  sp varchar(255),
  requestDate timestamp default 'now',
  primary key (id)
);