export const privacyProperties = [
  'whatData',
  'accessData',
  'country',
  'securityMeasures',
  'certification',
  'certificationLocation',
  'certificationValidFrom',
  'certificationValidTo',
  'surfmarketDpaAgreement',
  'surfnetDpaAgreement',
  'snDpaWhyNot',
  'privacyPolicy',
  'privacyPolicyUrl',
  'otherInfo',
]
